events {}

http {
  map $http_upgrade $connection_upgrade {
    default upgrade;
    "" close;
  }

  server {
    listen 3401;
    auth_basic "MLflow";
    auth_basic_user_file /etc/nginx/ops.htpasswd;

    location / {
      proxy_pass http://mlflow:5000;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }
  }

  server {
    listen 3403;
    auth_basic "Dagster";
    auth_basic_user_file /etc/nginx/ops.htpasswd;

    location / {
      proxy_pass http://dagster-webserver:3000;
      proxy_http_version 1.1;
      proxy_set_header Host $http_host;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection $connection_upgrade;
    }
  }

  server {
    listen 8080;

    location = /health {
      access_log off;
      default_type text/plain;
      return 200 "ok\n";
    }
  }
}
